// @ts-check

export const DEMO_VERSION = 'vmls-operations-2026-08-v4'
export const STORAGE_KEY = 'vmls:operations:2026-08:v4'

export const roles = Object.freeze([
  {
    id: 'agent',
    label: 'Môi giới',
    shortLabel: 'MG',
    group: 'Thị trường',
    defaultWorkspace: 'sellerDossiers',
    purpose: 'Gửi yêu cầu xác nhận quyền đại diện và hoàn thiện hồ sơ khách bán.',
  },
  {
    id: 'brokerage',
    label: 'Sàn môi giới',
    shortLabel: 'SÀN',
    group: 'Thị trường',
    defaultWorkspace: 'coordination',
    purpose: 'Theo dõi quyền đại diện, SLA và điểm nghẽn trong phạm vi sàn.',
  },
  {
    id: 'seller',
    label: 'Người bán',
    shortLabel: 'NB',
    group: 'Thị trường',
    defaultWorkspace: 'sellerRequests',
    purpose: 'Xác nhận quyền đại diện và cung cấp tài liệu của hồ sơ.',
  },
  {
    id: 'buyer',
    label: 'Người mua',
    shortLabel: 'NM',
    group: 'Thị trường',
    defaultWorkspace: 'purchaseDossiers',
    purpose: 'Xác nhận sẵn sàng công chứng và tiếp nhận kết quả.',
  },
  {
    id: 'bank',
    label: 'Ngân hàng',
    shortLabel: 'NH',
    group: 'Thị trường',
    defaultWorkspace: 'sharedDossiers',
    purpose: 'Xử lý các hồ sơ được đồng ý chia sẻ cho mục đích tài chính.',
  },
  {
    id: 'developer',
    label: 'Chủ đầu tư',
    shortLabel: 'CĐT',
    group: 'Thị trường',
    defaultWorkspace: 'contractTransfers',
    purpose: 'Tiếp nhận và xác nhận chuyển nhượng hợp đồng mua bán.',
  },
  {
    id: 'vmls',
    label: 'Vận hành VMLS',
    shortLabel: 'VMLS',
    group: 'Vận hành dữ liệu',
    defaultWorkspace: 'integrations',
    purpose: 'Theo dõi danh tính bản ghi, nguồn dữ liệu và sự kiện tích hợp.',
  },
  {
    id: 'notary',
    label: 'Văn phòng công chứng',
    shortLabel: 'VPCC',
    group: 'Đơn vị xử lý',
    defaultWorkspace: 'notaryDossiers',
    purpose: 'Tiếp nhận, kiểm tra và trả kết quả hồ sơ công chứng.',
  },
  {
    id: 'landRegistry',
    label: 'Văn phòng đăng ký đất đai',
    shortLabel: 'VPĐKĐĐ',
    group: 'Đơn vị xử lý',
    defaultWorkspace: 'landTransfers',
    purpose: 'Tiếp nhận hồ sơ đăng ký biến động và trả kết quả sang tên.',
  },
  {
    id: 'tax',
    label: 'Cơ quan thuế',
    shortLabel: 'THUẾ',
    group: 'Đơn vị xử lý',
    defaultWorkspace: 'taxDossiers',
    purpose: 'Theo dõi hồ sơ nghĩa vụ tài chính được đồng bộ về VMLS.',
  },
])

export const marketRoles = Object.freeze(
  roles.filter(({ id }) => ['agent', 'brokerage', 'seller', 'buyer', 'bank', 'developer'].includes(id)),
)

export const externalRoles = Object.freeze(
  roles.filter(({ id }) => ['vmls', 'notary', 'landRegistry', 'tax'].includes(id)),
)

export const workspaceDefinitions = Object.freeze({
  agent: [
    { id: 'applications', label: 'Ứng dụng' },
    { id: 'sellerDossiers', label: 'Hồ sơ khách bán' },
    { id: 'representedInventory', label: 'Nguồn hàng được đại diện' },
    { id: 'coBrokerRegistrations', label: 'Đăng ký cùng bán' },
    { id: 'listingDistribution', label: 'Phân phối Tin bán' },
    { id: 'properties', label: 'Bất động sản' },
    { id: 'listings', label: 'Tin bán' },
    { id: 'transactions', label: 'Giao dịch' },
  ],
  brokerage: [
    { id: 'applications', label: 'Ứng dụng' },
    { id: 'coordination', label: 'Điều phối hồ sơ' },
    { id: 'representedInventory', label: 'Nguồn hàng được đại diện' },
    { id: 'listings', label: 'Tin bán' },
    { id: 'dataQuality', label: 'Chất lượng dữ liệu' },
  ],
  seller: [
    { id: 'applications', label: 'Ứng dụng' },
    { id: 'sellerRequests', label: 'Yêu cầu xác nhận' },
    { id: 'properties', label: 'Bất động sản' },
    { id: 'listings', label: 'Tin bán' },
  ],
  buyer: [
    { id: 'applications', label: 'Ứng dụng' },
    { id: 'purchaseDossiers', label: 'Hồ sơ mua' },
    { id: 'contracts', label: 'Hợp đồng mua bán' },
  ],
  bank: [
    { id: 'applications', label: 'Ứng dụng' },
    { id: 'sharedDossiers', label: 'Hồ sơ được chia sẻ' },
  ],
  developer: [
    { id: 'applications', label: 'Ứng dụng' },
    { id: 'contractTransfers', label: 'Chuyển nhượng HĐMB' },
  ],
  vmls: [
    { id: 'applications', label: 'Ứng dụng' },
    { id: 'integrations', label: 'Tích hợp và nguồn' },
    { id: 'properties', label: 'Bất động sản' },
    { id: 'listings', label: 'Tin bán' },
    { id: 'transactions', label: 'Giao dịch' },
    { id: 'audit', label: 'Nhật ký' },
  ],
  notary: [
    { id: 'applications', label: 'Ứng dụng' },
    { id: 'notaryDossiers', label: 'Hồ sơ công chứng' },
  ],
  landRegistry: [
    { id: 'applications', label: 'Ứng dụng' },
    { id: 'landTransfers', label: 'Đăng ký biến động' },
  ],
  tax: [
    { id: 'applications', label: 'Ứng dụng' },
    { id: 'taxDossiers', label: 'Hồ sơ nghĩa vụ tài chính' },
  ],
})

export const sourceRegistry = Object.freeze([
  {
    id: 'source-357',
    name: 'Hệ thống thông tin về nhà ở và thị trường bất động sản',
    owner: 'Bộ Xây dựng',
    category: 'Nguồn dữ liệu công khai',
    dataCategory: 'Thông tin nhà ở và thị trường bất động sản',
    url: 'https://thongtinbds.moc.gov.vn/',
    capturedOn: '15/08/2026',
    screenshot: '/assets/demo/357-homepage-2026-08-15.png',
    connectionStatus: 'Đã đồng bộ',
    recordCoverage: 'Hai bản ghi Bất động sản có định danh và dấu thời gian nguồn.',
    lastCheckedAt: '2026-08-15T08:15:00+07:00',
  },
])

export const ecosystemConnections = Object.freeze([
  {
    id: 'vneid',
    name: 'VNeID',
    owner: 'Trung tâm dữ liệu quốc gia về dân cư',
    relationship: 'Điểm xác nhận người bán',
    direction: 'Nhận kết quả xác nhận',
    status: 'Chưa kết nối',
    url: 'https://play.google.com/store/apps/details?hl=vi&id=com.vnid',
    capturedOn: '15/08/2026',
    screenshot: '/assets/demo/vneid-google-play-2026-08-15.png',
    inputLabel: 'Dữ liệu gửi',
    inputFields: ['Mã yêu cầu', 'Mã định danh Bất động sản', 'Phạm vi đại diện', 'Thời hạn hiệu lực'],
    outputLabel: 'Dữ liệu nhận',
    outputFields: ['Kết quả', 'Thời điểm xác nhận'],
  },
  {
    id: 'source-357',
    name: 'Hệ thống thông tin về nhà ở và thị trường bất động sản',
    owner: 'Bộ Xây dựng',
    relationship: 'Nguồn tham chiếu công khai',
    direction: 'Tham chiếu nguồn',
    status: 'Đã đồng bộ',
    url: 'https://thongtinbds.moc.gov.vn/',
    capturedOn: '15/08/2026',
    screenshot: '/assets/demo/357-homepage-2026-08-15.png',
    inputLabel: 'Dữ liệu gửi',
    inputFields: ['Không có'],
    outputLabel: 'Dữ liệu nhận',
    outputFields: ['NPID', 'Dữ liệu Bất động sản', 'Phiên bản nguồn', 'Thời điểm cập nhật'],
  },
  {
    id: 'housenow',
    name: 'HouseNow · Căn hộ chung cư',
    owner: 'HouseNow',
    relationship: 'Kênh phân phối Tin bán',
    direction: 'Chuẩn bị dữ liệu gửi',
    status: 'Chưa phát hành',
    url: 'https://www.housenow.com.vn/can-ho-chung-cu',
    capturedOn: '15/08/2026',
    screenshot: '/assets/demo/housenow-can-ho-2026-08-15.png',
    icon: '/assets/demo/housenow-icon.png',
    inputLabel: 'Dữ liệu gửi',
    inputFields: ['PLID', 'Tiêu đề', 'Giá', 'Thông tin BĐS', 'Nội dung và ảnh được chọn'],
    outputLabel: 'Dữ liệu nhận',
    outputFields: ['Trạng thái bàn giao', 'Thời điểm cập nhật'],
  },
])

const monitoringProperties = Object.freeze([
  { propertyId: 'NPID-HN-22001', propertyLabel: 'Căn hộ A3-08 · Tây Hồ' },
  { propertyId: 'NPID-HN-22002', propertyLabel: 'Căn hộ B1-15 · Nam Từ Liêm' },
  { propertyId: 'NPID-HN-22003', propertyLabel: 'Nhà ở · Long Biên' },
  { propertyId: 'NPID-HN-22004', propertyLabel: 'Căn hộ C2-06 · Cầu Giấy' },
  { propertyId: 'NPID-HN-22005', propertyLabel: 'Nhà ở · Hà Đông' },
])

const monitoringStatuses = Object.freeze([
  { status: 'Chờ tiếp nhận', rawStatus: 'Hồ sơ mới chuyển đến' },
  { status: 'Đang xử lý', rawStatus: 'Đã tiếp nhận và phân công xử lý' },
  { status: 'Yêu cầu bổ sung', rawStatus: 'Chờ tài liệu bổ sung' },
  { status: 'Đã xử lý', rawStatus: 'Đã hoàn tất xử lý hồ sơ' },
  { status: 'Đang xử lý', rawStatus: 'Đang đối chiếu dữ liệu hồ sơ' },
])

const createMonitoringRows = ({ source, sourcePrefix, processingOrganization }) => Object.freeze(
  monitoringProperties.map((property, index) => Object.freeze({
    id: `MON-${source}-${String(index + 1).padStart(2, '0')}`,
    source,
    sourceCaseId: `${sourcePrefix}-${String(index + 51).padStart(3, '0')}`,
    caseId: null,
    propertyId: property.propertyId,
    transactionId: source === 'notary' ? null : `PTID-HN-${String(index + 151).padStart(5, '0')}`,
    propertyLabel: property.propertyLabel,
    status: monitoringStatuses[index].status,
    rawStatus: monitoringStatuses[index].rawStatus,
    processingOrganization,
    sourceUpdatedAt: `2026-08-${String(18 + index).padStart(2, '0')}T${String(8 + index).padStart(2, '0')}:20:00+07:00`,
    receivedAt: `2026-08-${String(18 + index).padStart(2, '0')}T${String(8 + index).padStart(2, '0')}:23:00+07:00`,
    history: [],
    actionable: false,
  })),
)

export const externalMonitoringFixtures = Object.freeze({
  notary: createMonitoringRows({
    source: 'notary',
    sourcePrefix: 'HSCC-HN-MON',
    processingOrganization: 'Văn phòng công chứng Minh Tâm',
  }),
  landRegistry: createMonitoringRows({
    source: 'landRegistry',
    sourcePrefix: 'VPDKDD-HN-MON',
    processingOrganization: 'Chi nhánh Văn phòng đăng ký đất đai Tây Hồ',
  }),
  tax: createMonitoringRows({
    source: 'tax',
    sourcePrefix: 'HST-HN-MON',
    processingOrganization: 'Cơ quan thuế khu vực Tây Hồ',
  }),
})

const maskedParty = (
  reference,
  displayName,
  phone,
  identityRef,
  roleLabel,
  organization = null,
) => ({
  reference,
  displayName,
  phone,
  identityRef,
  roleLabel,
  displayNameLabel: 'Họ tên',
  referenceLabel: `Mã định danh ${roleLabel}`,
  organization,
  masked: true,
})

const houseNowChannel = Object.freeze({
  id: 'housenow',
  name: 'HouseNow',
  icon: '/assets/demo/housenow-icon.png',
  status: 'Chưa phát hành',
  fieldScope: 'Tiêu đề, giá, thông tin BĐS, nội dung và ảnh được chọn',
  updatedAt: null,
})

const propertySourceRecord357 = ({
  npid,
  sourceRecordId,
  version,
  sourceUpdatedAt,
  receivedAt,
  propertyType,
  project,
  developer,
  location,
  building,
  unit,
  areas,
}) => ({
  sourceId: 'source-357',
  sourceName: 'Hệ thống thông tin về nhà ở và thị trường bất động sản',
  sourceRecordId,
  version,
  npid,
  publicationStatus: 'Đã công bố',
  sourceUpdatedAt,
  receivedAt,
  claims: [
    { field: 'propertyType', label: 'Loại Bất động sản', value: propertyType },
    { field: 'project', label: 'Dự án', value: project },
    { field: 'developer', label: 'Chủ đầu tư', value: developer },
    { field: 'location', label: 'Khu vực', value: location },
    { field: 'building', label: 'Tòa', value: building },
    { field: 'unit', label: 'Căn / thửa', value: unit },
    ...areas.map(({ label, value, unit: areaUnit }) => ({
      field: 'area',
      label,
      value: `${String(value).replace('.', ',')} ${areaUnit}`,
    })),
  ].filter(({ value }) => value !== null),
})

export const demoCases = Object.freeze([
  {
    id: 'sun-grand-thuy-khue',
    dossierId: 'HS-KB-HN-00031',
    title: 'Căn hộ S2-12A · Thụy Khuê',
    customerLabel: 'T••• M••• A•••',
    ownerLabel: 'N••• H••• N••',
    brokerageLabel: 'Sàn An Cư',
    priority: 'Bình thường',
    slaDueAt: '2026-08-27T17:00:00+07:00',
    expectedRoute: 'developer',
    property: {
      id: 'NPID-HN-09876',
      name: 'Căn hộ S2-12A',
      type: 'Căn hộ thuộc dự án',
      project: 'Sun Grand City Thụy Khuê Residence',
      unit: 'S2-12A',
      location: 'Thụy Khuê, Tây Hồ, Hà Nội',
      sourceRecord357: propertySourceRecord357({
        npid: 'NPID-HN-09876',
        sourceRecordId: '357-HN-09876',
        version: '2026-08-10.1',
        sourceUpdatedAt: '2026-08-10T08:20:00+07:00',
        receivedAt: '2026-08-10T08:25:00+07:00',
        propertyType: 'Căn hộ thuộc dự án',
        project: 'Sun Grand City Thụy Khuê Residence',
        developer: 'Sun Group',
        location: 'Thụy Khuê, Tây Hồ, Hà Nội',
        building: 'S2',
        unit: 'S2-12A',
        areas: [
          { label: 'Diện tích thông thủy', value: 69.2, unit: 'm²' },
          { label: 'Diện tích tim tường', value: 82.3, unit: 'm²' },
        ],
      }),
      areas: [
        {
          kind: 'usable',
          label: 'Diện tích thông thủy',
          value: 69.2,
          unit: 'm²',
          sourceId: 'SRC-HDMB-S2-12A',
          sourceLabel: 'Hợp đồng mua bán',
        },
        {
          kind: 'gross',
          label: 'Diện tích tim tường',
          value: 82.3,
          unit: 'm²',
          sourceId: 'SRC-HDMB-S2-12A',
          sourceLabel: 'Hợp đồng mua bán',
        },
      ],
      sourceRecords: [
        {
          id: 'SRC-HDMB-S2-12A',
          label: 'Hợp đồng mua bán đã che thông tin',
          documentRef: 'HDMB-S2-12A/2024',
          receivedAt: '2026-08-10T08:42:00+07:00',
        },
        {
          id: 'SRC-HS-BAN-S2-12A',
          label: 'Hồ sơ bên bán đã che thông tin',
          documentRef: 'HS-BAN-S2-12A',
          receivedAt: '2026-08-10T08:40:00+07:00',
        },
      ],
    },
    representation: {
      id: 'REP-HN-00031',
      confirmationId: 'XND-HN-00031',
      confirmationChannel: 'VNeID',
      allowedScopes: ['Độc quyền', 'Không độc quyền'],
    },
    listing: {
      id: 'PLID-HN-00125',
      transactionType: 'Chuyển nhượng',
      askingPrice: { value: 15800000000, displayValue: '15,8 tỷ đồng', currency: 'VND' },
      channel: houseNowChannel,
    },
    readiness: {
      agreement: {
        reference: 'TTCN-HDMB-HN-00031',
        type: 'Thỏa thuận chuyển nhượng HĐMB',
      },
      financeSharing: {
        shareId: 'CS-8F2D1A',
        purpose: 'Trao đổi nhu cầu tài chính',
        visibleFields: ['Loại bất động sản', 'Giá thỏa thuận', 'Mốc sẵn sàng'],
      },
    },
    notary: {
      id: 'HSCC-HN-00031',
      office: 'Văn phòng công chứng Minh Tâm',
      correlationId: 'VPCC-HN-260819-031',
      contractId: 'HDCC-HN-260822-031',
      requiredDocumentIds: ['seller-identity', 'buyer-identity', 'sale-contract', 'representation'],
      documents: [
        { id: 'seller-identity', label: 'Giấy tờ định danh bên bán' },
        { id: 'buyer-identity', label: 'Giấy tờ định danh bên mua' },
        { id: 'sale-contract', label: 'Hợp đồng mua bán' },
        { id: 'representation', label: 'Xác nhận quyền đại diện' },
      ],
      requiresSupplement: false,
      supplement: null,
    },
    externalProcessing: {
      notary: {
        source: 'notary',
        sourceCaseId: 'HSCC-HN-00031',
        processingOrganization: 'Văn phòng công chứng Minh Tâm',
        events: [
          {
            id: 'VPCC-EVT-00031-01',
            source: 'notary',
            sourceCaseId: 'HSCC-HN-00031',
            sequence: 1,
            status: 'Đang xử lý',
            rawStatus: 'Đã tiếp nhận và phân công xử lý',
            sourceUpdatedAt: '2026-08-19T10:00:00+07:00',
            receivedAt: '2026-08-19T10:02:00+07:00',
          },
          {
            id: 'VPCC-EVT-00031-02',
            source: 'notary',
            sourceCaseId: 'HSCC-HN-00031',
            sequence: 2,
            status: 'Đã xử lý',
            rawStatus: 'Đã ký hợp đồng công chứng',
            sourceUpdatedAt: '2026-08-22T15:30:00+07:00',
            receivedAt: '2026-08-22T15:31:00+07:00',
            effect: {
              type: 'notary_completed',
              contractId: 'HDCC-HN-260822-031',
              signedAt: '2026-08-22T15:30:00+07:00',
            },
          },
        ],
      },
      tax: {
        source: 'tax',
        sourceCaseId: 'HST-HN-00031',
        processingOrganization: 'Cơ quan thuế khu vực Tây Hồ',
        events: [
          {
            id: 'TAX-EVT-00031-01',
            source: 'tax',
            sourceCaseId: 'HST-HN-00031',
            sequence: 1,
            status: 'Đang xử lý',
            rawStatus: 'Đã tiếp nhận hồ sơ nghĩa vụ tài chính',
            sourceUpdatedAt: '2026-08-22T16:00:00+07:00',
            receivedAt: '2026-08-22T16:02:00+07:00',
          },
          {
            id: 'TAX-EVT-00031-02',
            source: 'tax',
            sourceCaseId: 'HST-HN-00031',
            sequence: 2,
            status: 'Đã xử lý',
            rawStatus: 'Đã ghi nhận hoàn thành nghĩa vụ tài chính',
            sourceUpdatedAt: '2026-08-23T16:00:00+07:00',
            receivedAt: '2026-08-23T16:03:00+07:00',
            effect: { type: 'tax_completed' },
          },
        ],
      },
      landRegistry: null,
    },
    transaction: {
      id: 'PTID-HN-00031',
    },
    transfer: {
      basis: 'Hợp đồng mua bán với chủ đầu tư',
      route: 'developer',
      intakeRef: 'CDT-HN-260824-031',
      resultRef: 'HDMB-MOI-S2-12A/2026',
      contractReference: 'HDMB-MOI-S2-12A/2026',
    },
    parties: {
      seller: maskedParty('NB-HN-0031', 'T••• M••• A•••', '09•• ••• 218', 'CCCD •••• 1842', 'Người bán'),
      buyer: maskedParty('NM-HN-0031', 'N••• V••• A•', '09•• ••• 506', 'CCCD •••• 5076', 'Người mua'),
      agent: maskedParty('MG-HN-0831', 'N••• H••• N••', '09•• ••• 831', 'Mã môi giới ••831', 'Người đại diện', 'Sàn An Cư'),
    },
    actionTimes: {
      request_seller_confirmation: '2026-08-10T09:07:00+07:00',
      confirm_representation: '2026-08-12T10:15:00+07:00',
      declare_buyer: '2026-08-14T14:20:00+07:00',
      verify_readiness: '2026-08-17T09:10:00+07:00',
      handoff_notary_dossier: '2026-08-19T09:45:00+07:00',
      developer_intake: '2026-08-24T09:00:00+07:00',
      developer_confirm_transfer: '2026-08-25T16:30:00+07:00',
      buyer_receive_contract: '2026-08-26T10:30:00+07:00',
    },
  },
  {
    id: 'phu-thuong-landed-home',
    dossierId: 'HS-KB-HN-00044',
    title: 'Nhà ở · Phú Thượng',
    customerLabel: 'L••• T••• H•••',
    ownerLabel: 'P••• Q••• M•••',
    brokerageLabel: 'Sàn An Cư',
    priority: 'Cao',
    slaDueAt: '2026-08-29T17:00:00+07:00',
    expectedRoute: 'landRegistry',
    property: {
      id: 'NPID-HN-10421',
      name: 'Nhà ở Phú Thượng',
      type: 'Nhà ở riêng lẻ',
      project: null,
      unit: null,
      location: 'Phú Thượng, Tây Hồ, Hà Nội',
      sourceRecord357: propertySourceRecord357({
        npid: 'NPID-HN-10421',
        sourceRecordId: '357-HN-10421',
        version: '2026-08-11.1',
        sourceUpdatedAt: '2026-08-11T07:55:00+07:00',
        receivedAt: '2026-08-11T08:00:00+07:00',
        propertyType: 'Nhà ở riêng lẻ',
        project: null,
        developer: null,
        location: 'Phú Thượng, Tây Hồ, Hà Nội',
        building: null,
        unit: 'Thửa 118',
        areas: [
          { label: 'Diện tích đất', value: 72, unit: 'm²' },
          { label: 'Tổng diện tích sàn', value: 216, unit: 'm²' },
        ],
      }),
      areas: [
        {
          kind: 'land',
          label: 'Diện tích đất',
          value: 72,
          unit: 'm²',
          sourceId: 'SRC-GCN-PTH-118',
          sourceLabel: 'Giấy chứng nhận',
        },
        {
          kind: 'floor',
          label: 'Tổng diện tích sàn',
          value: 216,
          unit: 'm²',
          sourceId: 'SRC-GCN-PTH-118',
          sourceLabel: 'Giấy chứng nhận',
        },
      ],
      sourceRecords: [
        {
          id: 'SRC-GCN-PTH-118',
          label: 'Giấy chứng nhận đã che thông tin',
          documentRef: 'GCN-T118-BD24',
          receivedAt: '2026-08-11T08:12:00+07:00',
        },
        {
          id: 'SRC-HS-BAN-PTH-118',
          label: 'Hồ sơ bên bán đã che thông tin',
          documentRef: 'HS-BAN-PTH-118',
          receivedAt: '2026-08-11T08:14:00+07:00',
        },
      ],
    },
    representation: {
      id: 'REP-HN-00044',
      confirmationId: 'XND-HN-00044',
      confirmationChannel: 'VNeID',
      allowedScopes: ['Độc quyền', 'Không độc quyền'],
    },
    listing: {
      id: 'PLID-HN-00208',
      transactionType: 'Bán',
      askingPrice: { value: 24600000000, displayValue: '24,6 tỷ đồng', currency: 'VND' },
      channel: houseNowChannel,
    },
    readiness: {
      agreement: {
        reference: 'HDMB-HN-00044',
        type: 'Hợp đồng mua bán nhà ở',
      },
      financeSharing: {
        shareId: 'CS-41C7E9',
        purpose: 'Trao đổi nhu cầu tài chính',
        visibleFields: ['Loại bất động sản', 'Giá thỏa thuận', 'Mốc sẵn sàng'],
      },
    },
    notary: {
      id: 'HSCC-HN-00044',
      office: 'Văn phòng công chứng Minh Tâm',
      correlationId: 'VPCC-HN-260818-044',
      contractId: 'HDCC-HN-260826-044',
      requiredDocumentIds: ['seller-identity', 'buyer-identity', 'land-certificate', 'representation'],
      documents: [
        { id: 'seller-identity', label: 'Giấy tờ định danh bên bán' },
        { id: 'buyer-identity', label: 'Giấy tờ định danh bên mua' },
        { id: 'land-certificate', label: 'Giấy chứng nhận' },
        { id: 'representation', label: 'Xác nhận quyền đại diện' },
      ],
      requiresSupplement: true,
      supplement: {
        reasonCode: 'MISSING_MARITAL_STATUS',
        documentType: 'Xác nhận tình trạng hôn nhân',
      },
    },
    externalProcessing: {
      notary: {
        source: 'notary',
        sourceCaseId: 'HSCC-HN-00044',
        processingOrganization: 'Văn phòng công chứng Minh Tâm',
        events: [
          {
            id: 'VPCC-EVT-00044-01',
            source: 'notary',
            sourceCaseId: 'HSCC-HN-00044',
            sequence: 1,
            status: 'Đang xử lý',
            rawStatus: 'Đã tiếp nhận và phân công xử lý',
            sourceUpdatedAt: '2026-08-18T10:45:00+07:00',
            receivedAt: '2026-08-18T10:47:00+07:00',
          },
          {
            id: 'VPCC-EVT-00044-02',
            source: 'notary',
            sourceCaseId: 'HSCC-HN-00044',
            sequence: 2,
            status: 'Yêu cầu bổ sung',
            rawStatus: 'Chờ bổ sung xác nhận tình trạng hôn nhân',
            sourceUpdatedAt: '2026-08-19T14:40:00+07:00',
            receivedAt: '2026-08-19T14:42:00+07:00',
            effect: {
              type: 'supplement_required',
              reasonCode: 'MISSING_MARITAL_STATUS',
              documentType: 'Xác nhận tình trạng hôn nhân',
              dueOn: '2026-08-21',
            },
          },
          {
            id: 'VPCC-EVT-00044-03',
            source: 'notary',
            sourceCaseId: 'HSCC-HN-00044',
            sequence: 3,
            status: 'Đang xử lý',
            rawStatus: 'Đã tiếp nhận tài liệu bổ sung',
            sourceUpdatedAt: '2026-08-20T09:40:00+07:00',
            receivedAt: '2026-08-20T09:42:00+07:00',
            effect: { type: 'supplement_received' },
          },
          {
            id: 'VPCC-EVT-00044-04',
            source: 'notary',
            sourceCaseId: 'HSCC-HN-00044',
            sequence: 4,
            status: 'Đã xử lý',
            rawStatus: 'Đã ký hợp đồng công chứng',
            sourceUpdatedAt: '2026-08-26T10:00:00+07:00',
            receivedAt: '2026-08-26T10:01:00+07:00',
            effect: {
              type: 'notary_completed',
              contractId: 'HDCC-HN-260826-044',
              signedAt: '2026-08-26T10:00:00+07:00',
            },
          },
        ],
      },
      tax: {
        source: 'tax',
        sourceCaseId: 'HST-HN-00044',
        processingOrganization: 'Cơ quan thuế khu vực Tây Hồ',
        events: [
          {
            id: 'TAX-EVT-00044-01',
            source: 'tax',
            sourceCaseId: 'HST-HN-00044',
            sequence: 1,
            status: 'Đang xử lý',
            rawStatus: 'Đã tiếp nhận hồ sơ nghĩa vụ tài chính',
            sourceUpdatedAt: '2026-08-26T11:00:00+07:00',
            receivedAt: '2026-08-26T11:02:00+07:00',
          },
          {
            id: 'TAX-EVT-00044-02',
            source: 'tax',
            sourceCaseId: 'HST-HN-00044',
            sequence: 2,
            status: 'Đã xử lý',
            rawStatus: 'Đã ghi nhận hoàn thành nghĩa vụ tài chính',
            sourceUpdatedAt: '2026-08-27T11:00:00+07:00',
            receivedAt: '2026-08-27T11:03:00+07:00',
            effect: { type: 'tax_completed' },
          },
        ],
      },
      landRegistry: {
        source: 'landRegistry',
        sourceCaseId: 'VPDKDD-HN-260826-044',
        processingOrganization: 'Chi nhánh Văn phòng đăng ký đất đai Tây Hồ',
        events: [
          {
            id: 'VPDKDD-EVT-00044-01',
            source: 'landRegistry',
            sourceCaseId: 'VPDKDD-HN-260826-044',
            sequence: 1,
            status: 'Đang xử lý',
            rawStatus: 'Đã tiếp nhận hồ sơ đăng ký biến động',
            sourceUpdatedAt: '2026-08-26T14:00:00+07:00',
            receivedAt: '2026-08-26T14:02:00+07:00',
          },
          {
            id: 'VPDKDD-EVT-00044-02',
            source: 'landRegistry',
            sourceCaseId: 'VPDKDD-HN-260826-044',
            sequence: 2,
            status: 'Đã xử lý',
            rawStatus: 'Đã hoàn tất đăng ký biến động',
            sourceUpdatedAt: '2026-08-28T14:30:00+07:00',
            receivedAt: '2026-08-28T14:32:00+07:00',
            effect: {
              type: 'land_registry_completed',
              resultRef: 'DKBD-HN-260828-044',
              approvedAt: '2026-08-28T14:30:00+07:00',
            },
          },
        ],
      },
    },
    transaction: {
      id: 'PTID-HN-00044',
    },
    transfer: {
      basis: 'Giấy chứng nhận quyền sử dụng đất',
      route: 'landRegistry',
      intakeRef: 'VPDKDD-HN-260826-044',
      resultRef: 'DKBD-HN-260828-044',
      contractReference: null,
    },
    parties: {
      seller: maskedParty('NB-HN-0044', 'L••• T••• H•••', '09•• ••• 731', 'CCCD •••• 2941', 'Người bán'),
      buyer: maskedParty('NM-HN-0044', 'V••• T••• L•••', '09•• ••• 945', 'CCCD •••• 9135', 'Người mua'),
      agent: maskedParty('MG-HN-0246', 'P••• Q••• M•••', '09•• ••• 246', 'Mã môi giới ••246', 'Người đại diện', 'Sàn An Cư'),
    },
    actionTimes: {
      request_seller_confirmation: '2026-08-11T08:38:00+07:00',
      confirm_representation: '2026-08-12T10:10:00+07:00',
      declare_buyer: '2026-08-14T15:20:00+07:00',
      verify_readiness: '2026-08-17T09:00:00+07:00',
      handoff_notary_dossier: '2026-08-18T10:30:00+07:00',
      submit_supplement_handoff: '2026-08-20T09:25:00+07:00',
    },
  },
])

export function getDemoCase(caseId) {
  return demoCases.find(({ id }) => id === caseId) ?? null
}

export function getActionTime(caseId, actionType) {
  return getDemoCase(caseId)?.actionTimes[actionType] ?? null
}
